name: Build Vue and Deploy Node App

on:
  push:
    branches:
      - main 

#on:
#  pull_request:
#    types: [closed]
#    branches:
#      - main
          
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 임시 서버인 ubuntu-latest 에 현재 git repository 정보 반영
    - name: Checkout repository
      uses: actions/checkout@v5

    # 임시 서버인 ubuntu-latest 에 node를 설치
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '22'

    # 임시 서버인 ubuntu-latest 에 프론트 폴더 안에서 지정한 명령어 수행
    - name: Build Vue app
      working-directory: frontapp
    # packagelock.json이 있으면 npm ci 없으면 npm i
      run: |
        npm ci
        npm run build
        
    # github actions 에 저장된 private key를 ubuntu에 복사 (이유 : ubuntu에는 key가 없음)
    - name: Setup SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

    # 서버에 접속하여 배포 실행 
    # scp 작은 규모의 파일을 옮기는것은 scp로 가능하다. 키를 기반으로 접속, 포트정보, 어느 파일을 어디로 옮길것인지 경로 frontapp/dist가 출발지점 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/${{ secrets.SSH_USER }}/deploy_project/server/public/ 이게 목표지점
    # ssh 명령어를 실행하는것임. ||<<<이건 or임 restart가 안되면 이거 실행하는거임.  "<<'EOF'"  이건 EOF라는 단어가 나올 때까지 명령 종료하지마라는 의미임
    - name: SSH into server and deploy
      run: |
        scp   -r -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} frontapp/dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/${{ secrets.SSH_USER }}/deploy_project/backend/public/
        ssh -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/deploy_project
            git pull origin main
            cd backend
            npm ci
            pm2 restart app || pm2 start app.js --name "app" -- prod
            pm2 save
          EOF

        echo '== build end ==='
        
